### ISSUE TITLE
vim-textobj-quote + neovim latest is broken

### ISSUE THREAD

**Issue by telemachus** [reedes/vim-textobj-quote#13]
vim-textobj-quote: 32cd093 (latest, I believe)
neovim: v0.2.0-1089-g8d139553 (full build info [here](https://gist.github.com/telemachus/51f48f365bb8f3a181c90c06b589be77))
macOS: 10.12.4

Problem: If I try to use quotes, I get raw escapes mixed with text. For example, if I type `It's`, I end up with this result: `It<t_x30x128><t_x30s>`. (Note that the 's' ends up inside the second bit of escape code.)

Please let me know if you need me to do anything else to debug the problem. Thanks.

**Comment by reedes** [comment]
I haven't used neovim recently and will see if I can install and reproduce issue.

**Comment by reedes** [comment]
#16 reports that this is working in neovim. Please reopen if not. Thanks.
