### ISSUE TITLE
educate for ellipsis, em/en-dash etc.

### ISSUE THREAD

**Issue by gour** [reedes/vim-textobj-quote#16]
Hello!

I'm considering to switch from Emacs to (neo)vim and looking for a decent replacement for Emacs' [typoel](https://github.com/jorgenschaefer/typoel) package which allows me to e.g. enter '...' and get ellipsis. Same with '--'/'---' for en/em-dash along with entering appropriate quotes like 'educate' with this plugin, so wonder if this plugin can help with it or some other hint to have a proper support when writing content (articles, blog posts etc.) using Markdown Extra markup?

**Comment by reedes** [comment]
Using `iabbrev --- —` commands in your .vimrc is the typical way to support such replacements. See the _pencil_ plugin's Readme for examples of abbreviations for buffer-specific configuration.

Last March a neovim release had problems with the educate feature of this plugin. I'm unsure of current status of issue #13. Please update if it's working (or not) for you. Thanks

**Comment by gour** [comment]
> iabbrev --- — commands in your .vimrc is the typical way to support such replacements.

Thank you. That works and shows there are many things to learn about Vim...

> See the pencil plugin's Readme for examples of abbreviations for buffer-specific configuration.

I'll do. Thanks!

> Last March a neovim release had problems with the educate feature of this plugin. I'm unsure of current status of issue #13. Please update if it's working (or not) for you. Thanks

I've installed latest nvim (NVIM v0.2.3-80-ga494c9991) and there is works.
