### ISSUE TITLE
scriptencoding utf-8 not allowed in sandbox

### ISSUE THREAD

**Issue by mcepl** [reedes/vim-textobj-quote#17]
When starting vim with the file which activates ``call textobj#quote#init`` (actually, neovim from git (commit neovim/neovim@e46534b42 ) I get this error:
```
Error detected while processing \
    /home/matej/.vim/pack/minpac/start/vim-textobj-quote/autoload/textobj/quote.vim:                                                                      
line    9:                                                                                 
E48: Not allowed in sandbox: scriptencoding utf-8
```
I don't know if it matters, we could use ``"\u02a4"`` instead of switching ``scriptencoding``.

After that something is wrong, e.g., ``:w`` says ``E13: File exists (add ! to override) ``, I have to run ``:w!`` to save the file.

**Comment by mcepl** [comment]
See my rumination on the pull request #18.

**Comment by mcepl** [comment]
This one happened when I run ``:e filename.rst``:
```
Error detected while processing function TextObjSettings[3]..textobj#quote#init[21]..textob
j#user#plugin:                                                                             
line    9:                                                                                 
E48: Not allowed in sandbox: command! -bang -bar -nargs=0 TextobjQuoteDefaultKeyMappings ca
ll g:__textobj_quote.define_default_key_mappings("<bang>" == "!") 
```
Why are all these commands running in the sandbox?

**Comment by mcepl** [comment]
OK, so it is not just neovim, I can reproduce https://github.com/reedes/vim-textobj-quote/issues/17#issuecomment-388247191 with vim8 (patch 1813).

**Comment by mcepl** [comment]
I can reproduce with vim8 as well (VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 11 2018 15:16:16)
Included patches: 1-1813).

**Comment by bergercookie** [comment]
Hi there,

I'm facing a similar issue with [this plugin](https://github.com/bergercookie/vim-debugstring). I'm apparently running in a sandbox when I open any ruby script from neovim. In your case why were you running in a sandbox in the first place?

Thanks,
Nikos

**Comment by mcepl** [comment]
Hmm, I am not sure, what happened, but I haven’t seen this issue some time already. Let’s not bother upstream with it.
