### ISSUE TITLE
"Error detected while processing function textobj#quote#init"

### ISSUE THREAD

**Issue by lunarrunner** [reedes/vim-textobj-quote#7]
Under Manjaro Linux, I have installed your package through vundle, pasted the [configuration](https://github.com/reedes/vim-textobj-quote#configuration) into my .vimrc, and I have the following error message every time I launch vim:
```
Error detected while processing function textobj#quote#init:
line	16:
E117: Unknown function: textobj#user#plugin
```

**Comment by reedes** [comment]
Have you installed the dependency https://github.com/kana/vim-textobj-user ?

**Comment by lunarrunner** [comment]
Oh… right. I missed that part somehow in the readme. I'm sorry.

If I may have a small suggestion, I think it might be a good idea to include that part about the dependency in the *Requirements* section rather than in *Installation*.
